services:
  orman-be:
    container_name: orman-be
    build:
      context: .
      network: host
    command: node index
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - 33004:3000